#! /bin/bash
# copy files
# first argument path of the directory which contains hdp mdpi xhdip xxhdpi xxxdpi
# second argument path of the android project
# emaple call cpdrawables sourcePath destinationAndroidProjectPath
mv -v $1/hdpi/* $2/app/src/main/res/drawable-hdpi
mv -v $1/mdpi/* $2/app/src/main/res/drawable-mdpi
mv -v $1/xhdpi/* $2/app/src/main/res/drawable-xhdpi
mv -v $1/xxhdpi/* $2/app/src/main/res/drawable-xxhdpi
mv -v $1/xxxhdpi/* $2/app/src/main/res/drawable-xxxhdpi
echo "--------------------Copied Successfully--------------------------"
