#! bin/bash
# rename and copy drawables
# first argument path of the directory which contains hdp mdpi xhdip xxhdpi xxxdpi
# second argument path of the android project
# third argument desired name of the assest
# example cprdawables sourcePath destinationAndroidProjectPath
mv -v $1/hdpi/* $2/app/src/main/res/drawable-hdpi/$3
mv -v $1/mdpi/* $2/app/src/main/res/drawable-mdpi/$3
mv -v $1/xhdpi/* $2/app/src/main/res/drawable-xhdpi/$3
mv -v $1/xxhdpi/* $2/app/src/main/res/drawable-xxhdpi/$3
mv -v $1/xxxhdpi/* $2/app/src/main/res/drawable-xxxhdpi/$3
echo "------------------Copied Successfully & renamed to $3------------------"
